Added back canary hash check CI job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -121,17 +121,17 @@ jobs:
         chmod a+x builder
         ./builder build -p ${{ env.PACKAGE_NAME }} default-downstream
 
-  # canary-hash-check:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Check S3 for canary log - ${{ env.PACKAGE_NAME }}
-  #       run: |
-  #         aws s3api head-object --bucket ${{env.AWS_S3_BUCKET}} --key ${{env.PACKAGE_NAME}}/${{env.COMMIT_SHA}}.log
-  #         if [[ $? == 0 ]]
-  #         then
-  #           echo "Canary log found!"
-  #         else
-  #           echo "Canary log was not found!"
-  #           exit 1
-  #         fi
+  canary-hash-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check S3 for canary log - ${{ env.PACKAGE_NAME }}
+        run: |
+          aws s3api head-object --bucket ${{env.AWS_S3_BUCKET}} --key ${{env.PACKAGE_NAME}}/${{env.COMMIT_SHA}}.log
+          if [[ $? == 0 ]]
+          then
+            echo "Canary log found!"
+          else
+            echo "Canary log was not found!"
+            exit 1
+          fi
 
